### ISSUE TITLE
Ruhum - Giving an account a credit limit in one market protects them from liquidation in all other markets

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#114]
Ruhum

high

# Giving an account a credit limit in one market protects them from liquidation in all other markets

## Summary
The admin is able to grant an account a credit limit for a given market. That allows them to borrow funds up to the limit without having to deposit any collateral. But, that prevents the account from being liquidatable in all the other markets.

## Vulnerability Detail
A user is deemed a credit account if it has a credit limit in at least one market:

```sol
    function isCreditAccount(address user) public view returns (bool) {
        return allCreditMarkets[user].length > 0;
    }
```

Credit accounts are protected from liquidation:
```sol
    function liquidate(
        address liquidator,
        address borrower,
        address marketBorrow,
        address marketCollateral,
        uint256 repayAmount
    ) external nonReentrant isAuthorized(liquidator) {
        // ...
        require(!isCreditAccount(borrower), "cannot liquidate credit account");
        // ...
    }
```

This poses a risk to the protocol as it increases the potential exposure it has to bad debt from that user.

There are some restrictions to a credit account:
- they are not able to deposit any new collateral
- in the market where they have the credit limit, they can't borrow more than that even if they have enough collateral.

But, that opens up the following issue:
- the account can frontrun the admin's `setCreditLimit()` tx to load the address with collateral.
- after receiving the credit limit it can then borrow funds from the other markets where it has no credit limit
- if that debt turns unhealthy, e.g. the collateral loses value you're not able to liquidate that position.

If the position is not liquidated in time you could run into a scenario where the position is not worth liquidating anymore. That could be the case if the collateral loses so much value that the borrowed funds are worth more than it. Or, if the borrowed funds gain in value.

## Impact
The protocol has increased exposure to bad debt because credit accounts can't be liquidated in markets where they **don't** have a credit limit.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L492-L492
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L240

## Tool used

Manual Review

## Recommendation
The liquidation protection should only be placed on the market where the account has a credit limit. All the other position's should be fully liquidatable.

**Comment by 0xruhum** [comment]
Escalate for 10 USDC

Credit limits allow users to borrow up to a certain amount in the market where the limit was granted. They are not supposed to protect the user from being liquidated in all the other markets. But, that's currently the case.

Before a user receives a credit limit they can freely borrow funds in all the different markets as long as they provide enough collateral. After being [given the credit limit](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L634), the address is now a "credit account" and can only borrow in markets where it has credit. The existing positions are still valid tho. If one of those positions goes under, you are not able to liquidate them because of the modifier [here](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L492). That will leave the protocol with bad debt that can't be cleared.

One attack vector would be to frontrun the `setCreditLimit` tx to borrow as much as you can using collateral that has a fluctuating price. That would allow you to create a position that can't be liquidated.

**Comment by 0xffff11** [comment]
'''
From the operation side, we will go through a rigorous review to check the contract before giving the credit limit. For example, the contract must have the ability to profit and ironBank must be the senior debt, etc. Normally, for the safety, we will leave some buffer for the credit limit, but not much. When the credit limit usage is almost full, we will have a discussion to decide if we need to increase the limit. It makes no sense to have a penalty for credit accounts since we expect the credit limit to be just slightly larger than the borrow amount. Not to mention, in the worst scenario, if the credit account won't repay (e.g exploit), adding a penalty won't help at all.
'''
Credit Limits will be carefully reviewed before being given. Therefore, for this to happen requires an admin error.

I can see the risk that the issue has though. I could still see it as a medium

**Comment by hrishibhat** [comment]
Result:
Low
Unique
The credit account role by nature is trusted since you have to trust someone to give them a completely uncollateralized loan.
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/98#issuecomment-1639594847

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xruhum](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/114/#issuecomment-1607642584): rejected
