### ISSUE TITLE
shealtielanz - Use `WBTC/USD` price feed rather than falling back to `WBTC/BTC` and `BTC/USD` feeds to calculate the price of `WBTC` to `USD`.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#132]
shealtielanz

medium

# Use `WBTC/USD` price feed rather than falling back to `WBTC/BTC` and `BTC/USD` feeds to calculate the price of `WBTC` to `USD`.

[Price Oracle](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/oracle/PriceOracle.sol#L30)
## Summary
The developers said in the documentation that they couldn't find the `WBTC/USD` price feed on `Chainlink` so they decided to use an alternative method to get the price, which may cause discrepancies in the actual price and could be exploited, so I did some research and found a way for the developers to get the `WBTC/USD` price feeds for accurate prices.
## Vulnerability Detail
The `IronBank` Docs [Link Here](https://docs.ib.xyz/lending-market/price-oracle)

It states as follows:

> There are some tokens that we cannot find the corresponding price feeds on Chainlink. Therefore, we use price feed alternative instead.
For WBTC, we use the combination of two price feeds WBTC/BTC and BTC/USD, to get the WBTC price in USD quote as the source.
> - WBTC/BTC: 0xfdFD9C85aD200c506Cf9e21F1FD8dd01932FBB23
> - BTC/USD: 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c

But this is not so, after my research, I found that you can get the price feed of any token to USD by making a request to `Chainlink` and they'll provide it and also make it available for use.
Just do as follows:
- Click this link https://data.chain.link/
- You can always request a new price feed by clicking on the `Request price feed` at the Top-Right, Link here ~ [Request Data Feed](https://chain.link/contact?ref_id=datafeeds&_ga=2.225795794.953922268.1685899202-1136617684.1679934424)

**This way you can get any price feed that isn’t on Chainlink right now and they'll create and send it to you.**
## Impact
Using getting the price of `WBTC/USD` via calculations with `WBT/BTC` and `BTC/USD` can cause deep discrepancies between the calculated price and the actual price if there is any issue or attack on any of the price feeds, and overall using the actual price feed improves the Protocol and mitigates any issue that could arise due to mistake in wrong calculation. 
## Code Snippet
- https://docs.ib.xyz/lending-market/price-oracle.
- https://chain.link/contact?ref_id=datafeeds&_ga=2.225795794.953922268.1685899202-1136617684.1679934424
## Tool used
`Manual Review` & `A Little Research `

## Recommendation
Used the actual price feed of `WBTC/USD` rather than calculating its price from `WBTC/BTC` and `BTC/USD` price feeds

**Comment by shealtielanz** [comment]
Escalate for 10 USDC
First of all thanks to 0xffff11, for the comment about this issue, but the fix I reccomended is a very good one, also how can you say that that you didn't find the feed for WBTC/USD but I showed you exactly how to get it and you said the issue is invalid, Using the price of different feeds can affect a protocol when there are issues with anyone. I think this should be a medium because I solve the problem the developers said the had, by showing them how to get the WBTC/USD fess, and thr issue is marked as will fix meaning the developers will make use of my Reccomendation, I wish you guys will reconsider and give me a reward for this issue.

**Comment by shealtielanz** [comment]
Yes your right ser, however if you use the method I described in my report. you can easily get the price feed of WBTC/USD from chainlink. even tho it's not available on Chainlink  right not you can get it by requesting it. I think this issue is similar to using wrong price feeds for an oracle, thereby it reaches sherlocks standard for a medium, even tho it might seems trival

**Comment by ibsunhub** [comment]
Some clarification:

1. We will use `WBTC/BTC` * `BTC/USD` as the price feed of WBTC. We forgot to support BTC as quote in the price oracle. Therefore, we will add a fix so that we can support WBTC/BTC price feed.
2. We never planed to use BTC/USD as the price of WBTC. We just thought there was a WBTC/USD price feed.

**Comment by shealtielanz** [comment]
Oh I understand, but in terms of what the documentation stated then, This is a valid medium Severity based on sherlock rules and request the Severity be raised to a medium, this is based on the developers assumption which was mildly mistaken.
Also My point is that you can actually get the price feed of WBTC/USD even though its doesn't exist by requesting it from chainlink, saying it doesn't exist is wrong as far as you could request it from chainlink

**Comment by ibsunhub** [comment]
fix: https://github.com/ibdotxyz/ib-v2/pull/52

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Based on the Sponsor comments this issue and its duplicates are not valid high/medium.
Using  WBTC/BTC * BTC/USD to get a price for WBTC is a design choice.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [shealtielanz](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/132/#issuecomment-1606115536): rejected

**Comment by IAm0x52** [comment]
Fix looks good. Oracle has been updated to support BTC as quote
