### ISSUE TITLE
berlin-101 - Missing extension whitelist opens attack vector for malicious extensions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#133]
berlin-101

medium

# Missing extension whitelist opens attack vector for malicious extensions

## Summary

The IronBank protocol embraces the concept of extensions. But it does not maintain a whitelist of trusted extensions that can be allowed for users. This creates the risk of malicious extensions being activated which can put funds at risk.

## Vulnerability Detail

The `setUserExtension` function of `IronBank.sol` allows the activation of extensions for a particular user. But it allows any address of an extension to be passed. The extension contract address is not checked against a global whitelist of allowed extension addresses that the project could maintain: https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L538-L550

In consequence any contract address could be passed and register a malicious extension for a user.

A malicious extension e.g. could be very similar to the `TxBuilderExtension` provided by the IronBank project so it would even withstand a quick review by the user.

It may for example only implement its `borrow` function slightly different so that the borrowed tokens are not sent to the user but to the attacker.

The extension will pass the check in the `_checkAuthorized` function: https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L782-L784

To add an extension an attacker may trick the user into calling `setUserExtension` with a malicious contract address.

This e.g. could happen in 2 ways:

1) Immitating IronBank with a malicous frontend application and making the user belief he is interacting with the real IronBank frontend.

2) Manipulating the IronBank frontend in a way that a malicious extension contract address is used by e.g. changing the value behind a user interface element (dropdown, checkbox). This could be caused for example by installing a malicious browser plugin.

Although a user must be tricked to sign a transaction, the difficulty of this attack is nevertheless to be considered low for the following reasons:

1) Since the activation of extensions is expected to be done via the IronBank frontend the user trusts the frontend to only fill in valid extension addresses for extension activation. Hence the user will not check the inputs of the transaction he signs. This is true for both ways of tricking the user listed before.

2) The user has very likely already signed transactions for the `IronBank` contract before and therefore may have added the contract to the list of known contracts (a feature supported by MetaMask). When executing the transaction from a malicious front-end application the user will think that he is safe since the IronBank contract is called which is already trusted.

## Impact

User can lose funds due to malicious extension that e.g. sends borrowed funds not to the user but to the attacker.

## Tool used

Manual Review

## Recommendation

The IronBank project should maintain a whitelist of addresses of trusted extensions and when calling `setUserExtension` the passed address should immediately be checked.

```Solidity
// added to IronBankStorage.sol
mapping(address => bool) public trustedExtensions;

// updated in IronBank.sol
function setUserExtension(address extension, bool allowed) external {
  require(trustedExtensions[extension], "Extension is untrusted!");
  // existing code of the function goes here
}
```

**Comment by snietert** [comment]
Escalated for 10 USDC

I think this is wrongly excluded. A wardens task is it to think about attack vectors that can get user funds lost. This also includes thinking about attack vectors that combine Web2 and Web3 vulnerabilities.

Faking a frontend to look exactly the same as the original is common practice among attackers and the financial barriers are low. E.g "Scammers create fake cryptocurrency trading platforms or fake versions of official crypto wallet to exploit victims. (https://news.trendmicro.com/2022/01/31/a-list-of-fake-crypto-websites-trading-platforms-2022/). At the same time the attack once established would be applicable to all users of the platform, which improves the cost/reward ratio for a potential attacker significantly.

In my opinion ,leaving the registration of new extensions open for any contract to be registered, unnecesseraly opens the attack vector of inluding a malicious extension. It could easily be prevented with a whitelist.

And in scenarios where the user already trusts the IronBank contract because of the list of known contracts (a feature supported by MetaMask) this is even more likely to happen.

This is not an issue to be excluded for "user input validation" as the user not willingly enters a malicious extension contract address. In this attack scenario the address is prefilled for him and he merely executes the transaction to register an extension. The reported issue also "identifies the core issue".

Given the described circumstance it could lead to significant loss for Ironbank's users.

A similar issue can be found here: https://solodit.xyz/issues/m-04-exactinput-allows-stealing-of-funds-via-a-malicious-pool-contract-code4rena-maverick-maverick-contest-git

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is not a smart contract issue and can be considered as a user input mistake. Frontend/Phishing scams are not valid medium/high based on sherlock rules.
