### ISSUE TITLE
0xStalin - Liquidations can be DoS if malicious borrower frontruns the liquidation tx and moves the liquidity that it has on the marketCollateral that will be used to seize funds to a different market

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#171]
0xStalin

high

# Liquidations can be DoS if malicious borrower frontruns the liquidation tx and moves the liquidity that it has on the marketCollateral that will be used to seize funds to a different market

## Summary
- Malicious borrowers can DoS the liquidation of their loans by frontrunning the liquidation transactions and moving their collateral among the different collateral markets, as a result of this, the liquidator will end up getting their transactions reverted even though the borrower is liquidable

## Vulnerability Detail
- As part of the liquidation process there is the seizure of funds from a marketCollateral that is specified by the liquidator.
  - The main problem occurs when the calculated amount of seized funds are attempted to be credited to the liquidator and deducted from the borrower, even though the _transferIBToken() doesn't make any external calls, as part of moving the seized funds from the borrower to the liquidator there is a [check that will make the liquidation tx to revert if the borrower doesn't have funds on the marketCollateral](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L873)

- A borrower can watch out for transactions that will liquidate their loans and identify that selected marketCollateral from where the seized funds will be taken, now the borrower knows from which market it needs to move funds so that the liquidation tx fails. The borrower frontruns the liquidation tx to move the funds from the marketCollateral to another market that is enabled as collateral

- **Example**
  - A borrower has a liquidable loan on Market A and has collateral on Market B & Market C.
  - The liquidator will repay the debt on Market A and chooses to receive collateral from Market C.
    - The borrower realizes its position will be liquidated and frontruns the liquidation transaction to do the following:
      - Supplies the same amount of the collateral that will remove from Market C into Market B, and right after supplying in Market B proceeds to redeem the collateral from Market C, leaving the borrower's balance in Market C totally empty.
    - Right after the malicious borrower updated its balances on the collateral markets, the transaction to liquidate the loan on Market B is executed, and when it tries to seize the borrower's collateral from Market C it will fail because at that point the borrower doesn't have any balance on Market C.

- The malicious borrower can continue to DoS the liquidation of its position by moving its liquidity among markets, and the liquidator will end up getting their transactions reverted even though the borrower is liquidable

## Impact
- Malicious Borrowers can DoS the liquidation of their positions by frontrunning the liquidation tx and moving their collateral among different markets
- Liquidators will get their transactions reverted even though the borrower is liquidable, and will end up spending gas for free

## Code Snippet
- [Transfer of the Seized Tokens in the specified marketCollateral by the liquidator](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L504-L506C23)

## Tool used
Manual Review

## Recommendation
- The recommendation would be to execute the[ `_transferIBToken()`](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L506) (transfer of the seized tokens) in a try-catch, and if the first attempt fails, catch the error and then re-attempt the transfer but this time the contract will determine from which market(s) can seize the collateral
  - By forcing a re-attempt of transferring the seized collateral if the first attempt fails, and allowing the contract to determine from which markets the collateral will be seized, there is no way that malicious borrowers can prevent their positions from being liquidated by moving their collateral among different markets.

**Comment by stalinMacias** [comment]
Escalate for 10 usdc
Why this issue was marked as excluded? Any user can cause the liquidation transactions to revert by simply moving their collateral among the different valid marketColalterals.
Liquidators will spend their gas on a transaction that has been frontrunned and the contract's state was modified to make the liquidation tx to revert, even though the borrower is still liquidable.

When the liquidation tx is sent to the blockchain, the liquidator defines the market of the collateral from where the funds will be seized, but if a malicious borrower frontruns the tx & just moves their funds from that market to another market when the liquidation tx is executed it will fail because the borrower has no funds on the chosen markets to seize the borrower's collateral

Could I get an explanation of why is this not considered a valid issue?

**Comment by 0xffff11** [comment]
Duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/255

**Comment by stalinMacias** [comment]
@0xffff11 Based on the answer given on #255 , I'm explaining a little bit differently how a borrower can prevent its positions from being liquidated, it has nothing to do with Liquidators making mistakes or not selecting the max amount (type(uint256).max) for the liquidation.
I'm describing how borrowers can escape liquidations, even if the liquidator attempts to liquidate 100% of the position (type(uint256).max)

The core issue I'm presenting is about borrowers moving their liquidity among the different available markets before the liquidation is executed, by doing this, when the liquidation is executed, and tries to claim the borrowed amount from the selected market it will fail because the borrower already moved its liquidity from that market to another market

Please could you take a second look at my issue

**Comment by hrishibhat** [comment]
@ibsunhub

**Comment by ibsunhub** [comment]
Invalid.

In your example, the malicious borrower wants to supply to market B and redeem from market C to avoid the liquidation. However, it's not possible to do so since the redeem function will check the account liquidity. If the check is passed, it means the borrower is no longer liquidatable.

**Comment by hrishibhat** [comment]
Result:
Invalid 
Unique
Considering this a non-issue based on above comment as it would fail the health check at the end of redeem call

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [stalinMacias](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/171/#issuecomment-1606172121): rejected
