### ISSUE TITLE
ast3ros - [M-2] Credit account can exceed credit limit without penalty

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#192]
ast3ros

medium

# [M-2] Credit account can exceed credit limit without penalty

## Summary

A credit account allows a user, typically a contract, to borrow up to a credit limit without providing collateral. However, there is no mechanism to enforce the credit limit or to liquidate the credit account if it accrues interest beyond the limit.

## Vulnerability Detail

A credit account enables a user, typically a contract, to borrow up to the credit limit without providing collateral. 

        if (isCreditAccount(from)) {
            require(from == to, "credit account can only borrow to itself");
            require(creditLimits[from][market] >= newUserBorrowBalance, "insufficient credit limit");

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L389-L391

However, when the credit account borrows the maximum limit, and time passes, the interest will accrue and make the user’s borrow balance increase over the credit limit. And there is no mechanism to force the credit account to repay. The credit account cannot be liquidated.

        require(!isCreditAccount(borrower), "cannot liquidate credit account");

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L492

## Impact

The credit account can borrow more than its credit limit, which violates the rule of Iron Bank. And there is no mechanism to bring the account back to the credit limit.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L389-L391

## Tool used

Manual Review

## Recommendation

Add a penalty when the credit account has a borrow balance over the credit limit. For example, increase the borrow rate or reduce the credit limit for the account. Alternatively, allow liquidation of the credit account if it exceeds the credit limit by a certain threshold.

**Comment by thangtranth** [comment]
Escalate for 10 USDC

Thank you sponsor for your input. I respect your opinion, but I would like to highlight the issue here that shows a valid attack vector when a credit account can have its borrow balance over the credit limit, which contradicts the design of the IronBank contract.

If the IronBankv2 relies on rigorous review and off-chain methods to prevent the issue related to credit account, then the credit account related issue should have been declared as out of scope in the beginning.

The proposed fix aims to create a negative economic incentive to discourage the normal credit accounts from doing so. It may not be effective in certain scenarios and other solutions may be required, but it does not mean ignoring that the issue exists.

**Comment by 0xffff11** [comment]
I agree with the miss-communication in the docs. This cases are very complex to judge because given the docs context it is an issue, but in reality, it is not. @hrishibhat  what do you think in this case?

**Comment by hrishibhat** [comment]
Result:
Low
Unique
The credit account role by nature is trusted since you have to trust someone to give them a completely uncollateralized loan.
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/98#issuecomment-1639594847

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/192/#issuecomment-1606151893): rejected
