### ISSUE TITLE
ast3ros - [M-3] The utilization rate does not account for the reserve amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#193]
ast3ros

medium

# [M-3] The utilization rate does not account for the reserve amount

## Summary

The utilization rate measures what percentage of the available funds in the market are used for lending. However, the current formula does not deduct the reserve amount from the total market value, which leads to an understated utilization rate and a wrong borrow rate.

## Vulnerability Detail

The utilization rate measure what percentage of the available funds in the market are using to lending. It is calculated using the getUtilization function:

        function getUtilization(uint256 cash, uint256 borrow) public pure returns (uint256) {
            if (borrow == 0) {
                return 0;
            }
            return (borrow * 1e18) / (cash + borrow);
        }

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/interest-rate-model/TripleSlopeRateModel.sol#L37-L42

However, this formula does not take into account the amount of funds that is taken into the protocol reserve and not available for borrowing. The correct formula should be:
        
        borrow  * 1e18 / (cash + borrow - reserve)

The reserve amount should be deducted because when interest is accrued, the `totalReserves` is increased by the `reservesIncreased` amount (the same as minting IB token to the reserve)

        totalReserves += reservesIncreased;

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L920

This will dilute the value of all other IB tokens by reducing the exchange rate. It also means that the total available funds for lending is decreased.

        ((m.totalCash + m.totalBorrow) * 1e18) / totalSupplyPlusReserves;

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L810

By not deducting the reserve, the calculation understates the utilization rate. This affects the calculation of the borrow rate, which depends on the utilization rate as an input.

## Impact

The utilization rate is understated and the borrow rate is incorrect.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/interest-rate-model/TripleSlopeRateModel.sol#L37-L42

## Tool used

Manual Review

## Recommendation

Deduct the reserve amount from the total available funds in the getUtilization function:

```diff
-        function getUtilization(uint256 cash, uint256 borrow) public pure returns (uint256) {
+        function getUtilization(uint256 cash, uint256 borrow, uint256 reserve) public pure returns (uint256) {
            if (borrow == 0) {
                return 0;
            }
-           return (borrow * 1e18) / (cash + borrow);
+           return (borrow * 1e18) / (cash + borrow - reserve);
        }
```

For example please check Compound calculation:  https://github.com/compound-finance/compound-protocol/blob/a3214f67b73310d547e00fc578e8355911c9d376/contracts/JumpRateModel.sol#L63-L70

**Comment by thangtranth** [comment]
Escalate for 10 USDC

Thank you sponsor for your feedback. I understand your point of view, but I would like to explain my analysis further:

- It is true that IBv2 stores reserves in the form of ibTokens instead of underlying. However, when it mints an amount of `reservesIncreased`, it lowers the exchange rate of `assets/ibToken`. This effectively removes a portion of funds from the market and makes it unavailable.

- utilization rate = `borrow / total available to borrow`: we can see clearly that `cash + borrow` is not the total available to borrow because some funds are taken for reservation.

As I recommended, the Compound calculation is only a reference and the fix will not be exactly the same. We will need to convert the reserved ibTokens to the assets first before deducting them from `cash + borrow`.
