### ISSUE TITLE
toshii - `softDelistMarket` does not correctly credit users for earned fees prior to updating the `reserveFactor`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#200]
toshii

medium

# `softDelistMarket` does not correctly credit users for earned fees prior to updating the `reserveFactor`

## Summary

Although `softDelistMarket` updates the `reserveFactor` for a given market, it doesn't first call `accrueInterest` for that market, which can result in lost fees for users

## Vulnerability Detail

All calls which can alter the interest rate model or reserve factor for a market are required to first call `accrueInterest` for that market. This is because those variables affect the amount of fees which will be paid out for users. This is done correctly in the `changeMarketInterestRateModel` and `adjustMarketReserveFactor` functions. However, there is no call of `ironBank.accrueInterest(market)` in the `softDelistMarket`. This can result in lost fees for users.

## Impact

`softDelistMarket` does not call `accrueInterest` for the given market prior to updating the `reserveFactor`, which can result in lost fees for users

## Code Snippet

Referenced lines of code:
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/MarketConfigurator.sol#L282-L299

## Tool used

Manual Review

## Recommendation

In the `softDelistMarket` function, following the require statement, add the following line:
```solidity
ironBank.accrueInterest(market);
```

**Comment by 0xToshii** [comment]
Escalate for 10 USD
Thank you for your review. This issue is a valid Medium because the current implementation of `softDelistMarket` in the MarketConfigurator contract will directly cause a loss of fees/interest for depositors in the market which is being soft delisted. This is because `accrueInterest` is not called on the IronBank contract prior to the the market's `reserveFactor` being set to `MAX_RESERVE_FACTOR`. When `reserveFactor` is set to `MAX_RESERVE_FACTOR`, this means that all the fees/interest since the last interest accruing activity will be lost for all depositors. 

As mentioned in the issue, this is clearly just an oversight, as the `adjustMarketReserveFactor` function behaves in the correct way, calling `accrueInterest` before updating the `reserveFactor`. Therefore, this is a valid Medium as per the definition: "causes a loss of funds but requires certain external conditions or specific states". Firstly, depositors lose out on the last period's interest as I explained, so loss of funds. Secondly, all it takes for this issue to occur is calling `softDelistMarket`, which is core functionality of the protocol.

**Comment by 0xffff11** [comment]
I think it is a Dup of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/426  Low

**Comment by 0xToshii** [comment]
> I think it is a Dup of #426 Low

I think this issue is fundamentally different than the one referenced in #426. #426 requires calling `softDelistMarket` -> `hardDelistMarket` -> `listMarket` (with the same parameters). Essentially it requires that the admin consciously makes all these choices, which has a low probability. 

Rather, in my issue, all that is required is that `softDelistMarket` is called, which is standard functionality that is required when a market is being prepared to be delisted. When this is done, almost all users will be unfairly losing out on fees which they should be receiving.

**Comment by ibsunhub** [comment]
This issue is not a dup of #426 .

However, I still see it as low.

- It is indeed an oversight and we will fix it.
- It's not the loss of funds since only the last period of supply interests will not be **credited** to suppliers.
- When a market is soft delisted, it often means it's inactive (very few supply and borrow).

**Comment by ibsunhub** [comment]
fix: https://github.com/ibdotxyz/ib-v2/pull/56

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering the impact of this issue a valid low based on the Sponsor's comment.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xtoshii](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/200/#issuecomment-1608196651): rejected

**Comment by IAm0x52** [comment]
Fix looks good. softDelistMarket now accrues interest before changing reserveFactor
