### ISSUE TITLE
sashik_eth - Oracles would not work on L2s

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#209]
sashik_eth

high

# Oracles would not work on L2s

## Summary

Oracles would not work on L2s.

## Vulnerability Detail

Iron Bank uses Chainlink protocol as an oracle service. The address of its feed registry is hardcoded during deployment in `PriceOracle.sol`:
```solidity
File: PriceOracle.sol
30:     constructor(address registry_, address steth_, address wsteth_) {
31:         registry = FeedRegistryInterface(registry_); 
32:         steth = steth_;
33:         wsteth = wsteth_;
34:     }
35: 
```

However, while Feed Registry exists on mainnet, it's not present on expected L2 chains (Arbitrum and Optimism):
https://docs.chain.link/data-feeds/feed-registry#contract-addresses

This would leave L2s instances of Iron Bank without access to current prices, breaking all core functionality.

## Impact

Oracles would not work on L2s, protocol functionality would be broken since no prices could be received. 

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/oracle/PriceOracle.sol#L31

## Tool used

Manual Review

## Recommendation

Consider updating oracle functionality in a way that it uses direct Chainlin price feeds instead of registry on L2s.

Duplicate of #191

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
Protocol is expected to be deployed on L2s, while the Chainlink feed registry isn't presented there meaning protocol would not work correctly.

**Comment by 0xffff11** [comment]
Sponsor comment: 
```
Regarding the mistake in the contest details mentioned in the README, we apologize for any confusion caused. When we stated that we would deploy on Arbitrum and Optimism, we meant that we would make the necessary modifications before deployment. This is our standard practice of maintaining contracts with different branches, same as what we did in v1: https://github.com/ibdotxyz/compound-protocol/branches

We are aware of the absence of a registry on OP and Arb, as pointed out by some individuals. We would like to inquire if it is possible to offer the minimum reward for an oracle issue on L2. Thank you.
```

**Comment by 0xffff11** [comment]
Even though the issue is valid, there will be no deployment on L2s as stated by sponsor. Unfortunately, it is invalid due to a miss-understanding from the docs

**Comment by sashik-eth** [comment]
Since issue #440 is also connected with L2 deployment and is currently judged as Medium, this issue should be valid High due to its impact.
 It is worth mentioning that Watsons considered the protocol would be deployed to L2s "as is" based on the information provided on the contest page. Therefore, I believe it is unfair to evaluate L2 issues based on the information provided by sponsors after the contest has ended, in terms of fairness in competition.

**Comment by 0xffff11** [comment]
I do agree with #440 also being an L2 deployment related and the judging of both issues should be tied together. I see this issue as more important than the other one. @hrishibhat Currently, all the l2 issues fall between the post-competition comment of sponsors saying that they won't deploy on L2, it was just to make it compatible in their github. So, it is trivial. In this case, I would validate this issue with at least a medium because there won't be actual lose of funds, once they would realize the first transactions fail because it does not work on l2's, they would just re-deploy. 

It is unfair for watsons to have this issue invalidated because of a miss-communication with sponsor. And, if that would happen, issue #440 should also be invalidated.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #191

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/209/#issuecomment-1606094212): accepted
