### ISSUE TITLE
BenRai - Increasing the liquidation threshold can make users instantly liquidatable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#246]
BenRai

medium

# Increasing the liquidation threshold can make users instantly liquidatable

## Summary

When the `MarketConfigurator` increases the liquidation threshold, there is no time lock before the adjustment comes into effect. This can make users instantly liquidatable without giving them a chance to repay the debt or increase the collateral first. 

## Vulnerability Detail

When the owner of the market configurator calls ` adjustMarketLiquidationThreshold` and increases the liquidation threshold of a market, this change comes into effect instantly without considering if thereby any user becomes liquidatable. Since the liquidationThreshold is used to calculate if a user can be liquidated, changing it can lead to instant liquidations of users without giving the users time to either repay his debt or increase his collateral. 

Example:

Bob deposits WETH worth 1000. The market has a collateralFactor of 50% so Bob borrows USDC worth 500 USD. The liquidation factor for the WETH market 60% so as long as the collateral is worth equal or more than (500 * 60%/50%) =  600 USD Bob cannot be liquidated. The value of the WETH  collateral Bob has deposited drops to 600 USD but Bob is still not liquidatable since he still does not meet the liquidation criteria. 

If the `MarketConfigurator` increases the liquidation factor of WETH from 60% to 65%, now the collateral need to be worth equal or more than: 500*65%/50% = 650 USD. Bob becomes instantly liquidatable without the time to repay his debt or deposit more collateral. 

## Impact

Users get instantly liquidated without the time to repay the debt or deposit more collateral

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/MarketConfigurator.sol#L205-L226

https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/IronBank.sol#L1084-L1085

## Tool used

Manual Review

## Recommendation

Implement a time lock when changing the liquidation threshold to give the user some time to repay the debt or increase the collateral to avoid liquidation.

**Comment by BenRai1** [comment]
escalate for 10 USD

Since there is a function to increase the liquidation threshold for a market, it is safe to assume that this function will be used to increase or decrease the liquidation threshold of markets at some point, making the scenario described above realistic. Since the possibility to liquidate a user is calculated over all the markets he has entered and we expect the Iron Bank to have a lot of users, increasing the liquidation threshold will most likely make some of the users instantly liquidatable. If this happens without the possibility to repay debt or increase collateral this will lead to a very bad user experience and will harm the reputation of the Iron Bank. Therefore in my opinion this issue is valid.

**Comment by 0xffff11** [comment]
Agree with med and duplication of #303 See my comment there

**Comment by 0xffff11** [comment]
I stand corrected on the above statement. The issue requires an admin mistake, therefore falls into the low category because they are trusted.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Admin is trusted for setting these values. Considering this issue a valid low
