### ISSUE TITLE
mert_eren - A user can redeem some lend token which he shouldn't after that he can liqudiate himself.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#313]
mert_eren

high

# A user can redeem some lend token which he shouldn't after that he can liqudiate himself.

## Summary
Protocol take security for immidiate liqudiate for giving differant threshold for _CheckAccountLiqudity and isLiqudatable by this way a borrower cannot make his account liqudatable with his hand accidently or purposely. Also, protocol reward liqudator with give bonus when calculate ratio. So if a borrower can use liqudiate himself instead of repay, he can take his lending tokens with pay less borrow token. In short a borrower cannot make himself liqudatable by his hand and protocol try to prevent this by check different levels of ratio when calculate for borrow&reddem amd liqudiate. However when redeem just accrue lended token and user can reddem more token than he should because his borrowed amount dont increase and protocol calculate his account liquidity ratio high than supposed to. After redeem there is a chance to his account liqudatable when accrueInterest use to borrow token and he can use liqudiate for his account with another account (aka sybil attack) so he pay less borrow token for take all of his lend token with liqudiate bonus and there is stuck some borrow amount to protocol normally it shouldn't for in that market situation.
## Vulnerability Detail
Poc steps are:
1)User lend and borrow one token with lowest ratio he can.
2)Use redeem function for himself after some time in that function protocol dont calculate borrow interest and he can reddem more token than he should.
3) Due to this unpredicted redeemed token amount his account become liquidatable and he liqudate his account with differant account.(Normally he will not be liqudatable because protocol dont allow him to reddem token.)
4) There is left some borrow amount for his account and 0 lending token.Normally if he want to take all l-his lending token he should repay all of borrow token and his account become 0 lend and 0 borrow token.    
## Impact
A malicious user can left some bad token for protocol in purpose. 
## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L406-L414
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1016-L1057
## Tool used

Manual Review

**Comment by merteren1234** [comment]
EscalaTe for 10 USDC.
I think #311 and #313 was not invalid reports. Because there is high chance for some tokens will not be updated and malicious users can be take benefit from them. For #313 if borrow token is not updated long time he can take unhealthy amount and make himself liquadatable and instead of repay he can use liqudiate (with differant account) and protocol will give all colleteral with less amount of cost for him(thanks to liquadation bonus) and harm protocol by stuck debt in contract. this can be also a problem which liqudiate healthy account as I indicate in #311. At the end if some tokens stay inactive in this protocol (when accrueInterest dont imply on them) there is possibly some serious problems can be occur so i think this reports should be valid due to root causes critical impacts for protocols and users.
Note: I think there is a chance to some tokens can be stay inactive long time and uncalculated accrue can be big because this protocol has just one liqudity pool unlike compound and if many tokens will be included to pool there is a high chance for users dont want to make operation on it but there is still some users can keep it as colletaral for borrow other tokens.

**Comment by 0xffff11** [comment]
I am struggling to understand the issue as the writing is quite poor. Is there any more context you can provide. The issue as of know seems invalid

**Comment by merteren1234** [comment]
i wanted to explain that issue which i reported is likely to be in future if users borrow unpopular token in the protocol. Also if this will be happened than protocol will harm from that because it will be like direct theft from protocol.(due to he will take his collateral token from protocol with liquidation bonus). So i think this issue can be considered as med chance high impact vulnerability and valid bug.

**Comment by ibsunhub** [comment]
I assume you are saying this scenario:
1. User supplies A and utilizes all his borrowing power to borrow B, and B market is not very active.
2. User redeems some A tokens.
3. User liquidates himself.

The issues is flawed.

For (2), why is the user able to redeem A tokens? It's not about the borrow interests. He shouldn't redeem anything if he used almost his borrowing power in step (1).

For (3), it's fine for a user to liquidate himself. From the protocol's point of view, the liquidation prevents the bad debt. It's not important who is the liquidator.

Also, the bad actor may not be able to liquidate himself since he needs to compete all other liquidation bots across the network. Even if he did liquidate himself, it's still not profitable since the [multiplication of the liquidation threshold and the liquidation bonus must be smaller than 100%](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/MarketConfigurator.sol#L244). For example, a user supplies 1,000 USDT (liquidation threshold = 85% & liquidation bonus 105%). If his USDT is being liquidated by himself, he will lose 15% and only earn 5% bonus.

Last, this issue mention the market being unpopular. This is also false assumption. The listing process is not permissionless. We will go through a review process to assess a token listing.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique 
Considering this a non-issue based on the Sponsor's comment

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [merteren1234](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/313/#issuecomment-1606083015): rejected
