### ISSUE TITLE
0xpinky - PToken.sol : `function absorb` is public and it can be called by anyone

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#483]
0xpinky

high

# PToken.sol : `function absorb` is public and it can be called by anyone

## Summary

`PToken.sol` has the [absorb ](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/token/PToken.sol#L63-L69) function which will be called by the contracts to absorb the any surplus amount of asset.

But the function is public and can be called by any by inputting the user address as argument.

## Vulnerability Detail

     * @notice Absorb the surplus underlying asset to user.
     * @dev This function should only be called by contracts.
     * @param user The beneficiary to absorb the surplus underlying asset
     */
    function absorb(address user) public {
        uint256 balance = IERC20(underlying).balanceOf(address(this));

        uint256 amount = balance - totalSupply();
        _mint(user, amount);
    }

It is clear and the function could be called by anyone since it has `public` modifier.

## Impact

Anyone can call and have the surplus token in their custody.
When the asset price is determined in any of the function call using the contract's balance, the bad actor can forcefully inject these assets which would cause the asset price manipulation.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/token/PToken.sol#L59-L68

## Tool used

Manual Review

## Recommendation

Remove the modifier 'public' and have the 'internal'

**Comment by 0xpinky** [comment]
Escalate for 10 USDC

Escalating this as there is no clarification on why this was excluded.

There is clear evidence of lack of access restriction.

Since the intention of function should be called only by the contract. But this has public access, so that anyone can call and takeaway the excess fund. 

Looking for further feedback and clarifications.

**Comment by 0xffff11** [comment]
The issue was discussed internally with sponsor:

"""
The absorb function is mainly for extension: https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/extensions/TxBuilderExtension.sol#L378-L379

and any other external contract who wants to implement similar actions therefore I disagree to make it a privilege function.
"""
I clearly see that anyone can mint to their own address, which shouldn't happen. Will re-check

**Comment by hrishibhat** [comment]
@ibsunhub could you provide your input on this issue?

**Comment by ibsunhub** [comment]
Invalid.

The function is "advised" not to be called by an EOA if the user wants to utilize this function to mint pToken. However, this function by its name is to be used to absorb the surplus balance in pToken contract. Anyone including an EOA has the right to do so. Therefore, we don't intend to make this function a privilege one.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low based on Sponsor's comment

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xpinky](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/483/#issuecomment-1608560080): rejected

**Comment by 0xpinky** [comment]
not sure why sherlock is blindly following sponsor feedback to decide the severity of a finding.. why don't have its own criteria. ?

@hrishibhat @0xffff11

**Comment by ibsunhub** [comment]
1. Again, the function is designed to absorb the "surplus" balance by anyone. We had the comment message just to remind that if an EOA wants to mint a pToken, use `wrap` function. Do not try to transfer the underlying and absorb the balance.
2. No one says the price of pToken is manipulatable under this situation. The price of a pToken is equal to its underlying. Don't imagine a problem that doesn't exist.
3. Your recommendation is to make this function "internal". This will make this function not accessible to anyone including a smart contract. This recommendation will make this function useless.

You are looking for further feedback and clarifications and I was giving an explanation. Why is this blindly following sponsor's feedback? If you think the explanation is not persuasive enough, you can point it out. Also, speaking of criteria, which part of this problem do you think is high in severity?

**Comment by 0xpinky** [comment]
may be my suggestion not good.. but I am surprised to see a token mint function with public modifier. I am not convinced with your explanation for making the mint function as public.

**Comment by ibsunhub** [comment]
I think you misunderstood what pToken is.

First, `absorb` function is not intended to be used to mint pToken. It's used to absorb the surplus balance in pToken contract. But transferring the underlying directly into pToken contract with `absorb` can also achieve the effect of minting pToken. It provides another way for **smart contracts** to mint pToken, not for EOAs. Therefore, we left the comment to remind EOAs not to try this.

Then, the "mint" and "burn" function for EOAs are `wrap` and `unwrap`. Even so, mint function is supposed to be public in pToken contract. Otherwise, how can a user wrap the underlying to mint pToken? It's like WETH for anyone to wrap native Ether into WETH. Of course the mint function should be public. It's not a governance token...
