### ISSUE TITLE
0xpinky - TxBuilderExtension.sol : `repayNativeToken` does not return the excess funds to the user.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#489]
0xpinky

medium

# TxBuilderExtension.sol : `repayNativeToken` does not return the excess funds to the user.

## Summary

[repayNativeToken](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L290) has the logic when the `repayAmount > borrowBalance`, only the `repayAmount - borrowBalance` is transferred to the user.

## Vulnerability Detail

as shown in below code, only the `repayAmount - borrowBalance` amount is sent to user when the condition `if (repayAmount > borrowBalance)` is satisfied.

    function repayNativeToken(address user) internal nonReentrant {
        uint256 repayAmount = msg.value;

        ironBank.accrueInterest(weth);
        uint256 borrowBalance = ironBank.getBorrowBalance(user, weth);
        if (repayAmount > borrowBalance) {
            WethInterface(weth).deposit{value: borrowBalance}();
            IERC20(weth).safeIncreaseAllowance(address(ironBank), borrowBalance);
            ironBank.repay(address(this), user, weth, borrowBalance);
            (bool sent,) = user.call{value: repayAmount - borrowBalance}(""); --------------------------------->>> audit find
            require(sent, "failed to send native token");
        } else {
            WethInterface(weth).deposit{value: repayAmount}();
            IERC20(weth).safeIncreaseAllowance(address(ironBank), repayAmount);
            ironBank.repay(address(this), user, weth, repayAmount);
        }
    }

## Impact

Any excess amount that was sent by user would be loss to the end user.
It may not be always possible to send the exact amount due to price updates.  So, in order to complete the transaction, user would send excess funds in order to fully repay.

We can attribute this situation to the real life situation too when we try to purchase something, at times we used to pay more and get in return what is left.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L290-L306

## Tool used

Manual Review

## Recommendation

    function repayNativeToken(address user) internal nonReentrant {
        uint256 repayAmount = msg.value;

        ironBank.accrueInterest(weth);
        uint256 borrowBalance = ironBank.getBorrowBalance(user, weth);
        if (repayAmount > borrowBalance) {
            WethInterface(weth).deposit{value: borrowBalance}();
            IERC20(weth).safeIncreaseAllowance(address(ironBank), borrowBalance);
            ironBank.repay(address(this), user, weth, borrowBalance);

            (bool sent,) = user.call{value: repayAmount - borrowBalance}(""); -------------->> ----- remove 

            (bool sent,) = user.call{value: repayAmount}(""); --------------------------------->> ++++ add

            require(sent, "failed to send native token");
        } else {
            WethInterface(weth).deposit{value: repayAmount}();
            IERC20(weth).safeIncreaseAllowance(address(ironBank), repayAmount);
            ironBank.repay(address(this), user, weth, repayAmount);
        }
    }
Duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/198

**Comment by 0xpinky** [comment]
Escalate for 10 USDC

I am not sure why this was excluded, also there is no explanation for that.

Refunding the excess amount would be fair. Since excess fund is not refunded, user will incur unnecessary loss.

Lets consider the following situation where excess fund would be sent to interact with contract.

1. Sending exact amount may not be feasible to complete the transaction since the fluctuation of tx gas happen more frequently.
2. Sometime user would send too much of amount my mistake. On one hand this can be attributed as user error but on the other hand it may happen inadvertently. in the second case , refunding the excess amount would be fair.  For example, if 10 was required, they may add one more zero by mistake, so the total value would be 100. In this case, user would loss 90 .

Since the protocol is going to be used by the public extensively, not refunding the excess amount would result in disincentivizing the user participation. In this case, it would be losing the user.

Avoiding 1 bad impression would be better that getting the 100 user, because that single user would cause reputational damage which would result in lack of attraction among public towards the system.

**Comment by 0xffff11** [comment]
Thanks you have my comment in #198

**Comment by 0xpinky** [comment]
Thanks you!

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #198 
Considering this issue a low based on the comment 
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/198#issuecomment-1637794678

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xpinky](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/489/#issuecomment-1608558440): rejected

**Comment by 0xpinky** [comment]
not sure why sherlock is blindly following sponsor feedback to decide the severity of a finding.. why don't have its own criteria. ?

**Comment by hrishibhat** [comment]
@0xpinky 
This issue is invalidated based on Sherlocks criteria. Extensions and routers are generally not designed to hold funds. 
Not refunding excess amount to the user sent by mistake or extra funds sent just to be sure is not a valid high/medium based on sherlock rules.
