### ISSUE TITLE
0xpinky - `ironBank.accrueInterest` is not called when calling the `getSupplyBalance` and `getBorrowBalance`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#499]
0xpinky

high

# `ironBank.accrueInterest` is not called when calling the `getSupplyBalance` and `getBorrowBalance`

## Summary

Prior to calling the `getSupplyBalance`, the function  `accrueInterest` should be called. This is done in order to use the accumulated value by considering the interest accrued for the particular duration.

We can see this, and the contract has done it in many places, except in few locations.

## Vulnerability Detail

when redeeming the native token, contract calls the `getSupplyBalance` incase of full redeem.

The function `getSupplyBalance` is called without calling the` accrueInterest`. This would lead to calculating the lesser redeem amount than the original value.

    function redeemNativeToken(address user, uint256 redeemAmount) internal nonReentrant {
        if (redeemAmount == type(uint256).max) {
            redeemAmount = ironBank.getSupplyBalance(user, weth);
        }
        ironBank.redeem(user, address(this), weth, redeemAmount);
        WethInterface(weth).withdraw(redeemAmount);
        (bool sent,) = user.call{value: redeemAmount}("");
        require(sent, "failed to send native token");

## Impact

Lesser amount calculation than what is actually it should be.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L275-L282

One more place I see in out scope contract.

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/lens/IronBankLens.sol#L157-L171

## Tool used

Manual Review

## Recommendation

Call the accrueinterset function. before calling the Supply balance and borrow balance.

**Comment by 0xpinky** [comment]
Escalate for 10 USDC

Escalating this as there is no clarity for why this was excluded.

When we look at the contract, before getting the `getSupplyBalance` , [accrueInterest](https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/IronBank.sol#L284) is called. This has been done in order to accrue the interest value and use it in further calculation.

For example, refer the following links, where the `accrueInterest` is called and used with output amount.

https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/extensions/TxBuilderExtension.sol#L341C1-L342

https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/extensions/TxBuilderExtension.sol#L392C1-L393

But [here ](https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/extensions/TxBuilderExtension.sol#L276C1-L278)it is not done.

In my report, I have mentioned this issue in scope as well as out of scope contract file. The same was checked with sponsor as well.

Thanks!

**Comment by 0xffff11** [comment]
I think the issue should be a valid high due to failing of accruing interests. It also has some duplicates

**Comment by ibsunhub** [comment]
Disagree with the severity.

This issue is the same with #360.

**Comment by ibsunhub** [comment]
@0xffff11 

#341 #34 are the dup to this issue.

#201 #109 #11 are another issues and I think it's also invalid. Same reason with[ this one](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/116#issuecomment-1608908346). It's a trade-off between gas efficiency and interest optimization. If we accrue the interests on every user entered markets, it would be onerous to use. This approach is the same with Compound-v2.
https://github.com/compound-finance/compound-protocol/blob/master/contracts/Comptroller.sol#L738
https://github.com/compound-finance/compound-protocol/blob/master/contracts/CToken.sol#L191

#41 #21 are invalid. I commented on those issues.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Given the discussions around accruing interest across multiple issues, the protocol response in the comment below justifies the design choice. 
They may have been historical decisions on a more complex protocol functioning, in a lending protocol like Iron bank this is a design trade-off to save gas. 
And for such issues to be considered a valid medium they must have a larger impact and it must not be considered an acceptable risk by the protocol. 
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/116#issuecomment-1608908346

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xpinky](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/499/#issuecomment-1608531154): rejected
