### ISSUE TITLE
rvierdiiev - UniswapExtension.uniswapV3SwapCallback will not work for !isExactInput

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#56]
rvierdiiev

high

# UniswapExtension.uniswapV3SwapCallback will not work for !isExactInput

## Summary
UniswapExtension.uniswapV3SwapCallback will not work for !isExactInput, because no transfer will be performed to the middle pools in the path.
## Vulnerability Detail
In order to pay uniswap pool for the swap, UniswapExtension.uniswapV3SwapCallback should transfer output token.
This is done correctly for the [`isExactInput` case](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L283).

But for the `isExactInput` case, token transfer [is located inside `else` clause](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L317), which means that for the pools in the middle of path transfer will not be performed, so swap will be reverted by uniswap then.
## Impact
It will be not possible for user to close his short position that he already opened.
## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L237-L320
## Tool used

Manual Review

## Recommendation
Do it in same way as it's [done for uniswap v2](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L422). Transfer should be outside of if/else.

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc. I believe this was wrongly excluded.

**Comment by 0xffff11** [comment]
Issue seems right. @ibsunhub thoughts?

**Comment by ibsunhub** [comment]
No, the issue is invalid.

For Uniswap v3 exact output swap, the extension process the flash swap in reverse order. If there are multiple pools, the extension will initiate the next swap recursively until the last pool. Also, it will make the current pool as the recipient of the next swap.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L301

That's the reason why the extension doesn't need to perform a transfer in every exact output swap except for the last one.

For Uniswap v3 exact input swap, the extension process the flash swap in normal order. However, we can't make the next pool as the recipient of this swap since the next swap hasn't started yet. Therefore, we need to set the extension as the recipient during every swap.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L253

That's the reason why the extension needs to repay to every involved pools.

For Uniswap v2 swap, we can't set the recipient during a flash swap so the extension needs to perform the transfer whether it is an exact input swap or an exact output swap.

**Comment by hrishibhat** [comment]
@rvierdiyev seems like a non-issue based on the sponsor's comment. 
Do you have additional comments?

**Comment by rvierdiyev** [comment]
no, i believe that sponsor is correct

the only thing
> For Uniswap v2 swap, we can't set the recipient during a flash swap so the extension needs to perform the transfer whether it is an exact input swap or an exact output swap.

you can set recipient as well
https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Pair.sol#L159C61-L159C63

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comments.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/56/#issuecomment-1606906897): rejected
