### ISSUE TITLE
0xHati - Ironbank#repay can be front run when uint256.max is used as amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#72]
0xHati

medium

# Ironbank#repay can be front run when uint256.max is used as amount

## Summary
The repay function within Ironbank.sol lets users repay their tokens borrowed. It's possible to repay for someone else and set the amount to uint256.max to indicate to pay the total loan back. This can be front run by the beneficiary to abuse the initiator. 

## Vulnerability Detail
`_repay` is called from `repay` like this:
```solidity
_repay(m, from, to, market, amount)
```
It's possible to repay on behalf of someone else by supplying a different 'to' than 'from', it's also possible for `to`, which will be the sender (see: `isAuthorized` modifier) to indicate to repay the full amount by passing `uint256.max` as the amount.
However 'to' can monitor that and front run the transaction by borrowing more. It's understandable why the `uint256.max` option is there since the amount passed won't be accounting for the interest accrued. To not leave dust uint256.max can be used. However, this opens up a vulnerability where this can be front run. 
For example:
User A supplies and borrows from market Z amount 100.
User B wants to repay user A and passes in uint256.max
User A front runs and borrows more until the maximum allowance/amount user B has

## Impact
When repaying on behalf of someone else this can be front run by the receiver and borrow more tokens and get them immediately from the initiator.
## Code Snippet
[repay](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L460)
[_repay](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L995)
## Tool used

Manual Review

## Recommendation
Only allow uint256.max if `to == from` in repay.

**Comment by 0xHati** [comment]
Escalate for 10 USDC. Any comments as to why this is excluded?

**Comment by 0xffff11** [comment]
Duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/255

**Comment by hrishibhat** [comment]
@0xHati 
Can you show from the perspective of the code how this happens?
> User B wants to repay user A and passes in uint256.max
> User A front runs and borrows more until the maximum allowance/amount user B has

**Comment by boulderbytes** [comment]
First of all thanks for coming back to this, I don't think this is a correct duplicate. The other issue is a dos, while in my case the user paying back on behalf of someone else will unknowingly lose funds.

Can you clarify what part is unclear to you? 

Basically the issue is this:
- you can use uint.max to pay back everything. 
- Secondly, you can pay back for another user or account by providing another address in "to". 

When uint.max is used and you pay back for another user, the beneficiary (the "to", can see that in the mem pool, open a new loan, or increase debt before the repay transaction goes through. When the repay transaction then happens it will pay back the new loan as well. Basically stealing money from the payer.

See: https://solodit.xyz/issues/borrowrepay-calls-race-condition-can-be-exploited-to-repay-more-than-expected-trailofbits-aave-protocol-pdf

**Comment by hrishibhat** [comment]
@ib-tycho @ibsunhub

**Comment by ibsunhub** [comment]
I don't see a vulnerability here. Why would someone want to repay full for a stranger?
If you want to repay for other user that you don't trust, you need to be careful of this. It's like approve an ERC20 token to a stranger. The repay on behalf functionality is used for better flexibility. For example, TxBuilderExtension uses it to achieve repaying WETH with native ETH. You could also develop your own contract. And the contract might utilize this functionality to manage your position / save costs / facilitate your daily operation, etc.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on sponsor's comment

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xHati](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/72/#issuecomment-1606059915): rejected
