### ISSUE TITLE
deadrxsezzz - A credit account user may not be able to redeem their funds even though they should be able to

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#98]
deadrxsezzz

medium

# A credit account user may not be able to redeem their funds even though they should be able to

## Summary
A credit account user might be unable to redeem their stake. 

## Vulnerability Detail
Consider the following scenario: User A has some stake in IronBank. He is then given a large creditLimit, which he uses and takes out a large borrow. The user can no longer withdraw their stake, since when calling `redeem`, `_checkAccountLiquidity(from);` is called. Since the borrowed amount costs significantly more than the user's stake, `_checkAccountLiquidity` will always revert. The only way for the user to withdraw their money is if they repay their loan, which basically makes the user's stake the same as collateral - the user cannot get ahold of it until he repays back his loan. This completely destroys the purpose of Credit Accounts and Credit Limits. 

```solidity
function _checkAccountLiquidity(address user) internal {
        uint8 status = liquidityCheckStatus[user];

        if (status == LIQUIDITY_CHECK_NORMAL) {
            (uint256 collateralValue, uint256 debtValue) = _getAccountLiquidity(user);
            require(collateralValue >= debtValue, "insufficient collateral");
        } else if (status == LIQUIDITY_CHECK_DEFERRED) {
            liquidityCheckStatus[user] = LIQUIDITY_CHECK_DIRTY;
        }
    }
```
```solidity
function _getAccountLiquidity(address user) internal view returns (uint256, uint256) {
        uint256 collateralValue;
        uint256 debtValue;

        address[] memory userEnteredMarkets = allEnteredMarkets[user];
        for (uint256 i = 0; i < userEnteredMarkets.length; i++) {
            DataTypes.Market storage m = markets[userEnteredMarkets[i]];
            if (!m.config.isListed) {
                continue;
            }

            uint256 supplyBalance = m.userSupplies[user];
            uint256 borrowBalance = _getBorrowBalance(m, user);

            uint256 assetPrice = PriceOracleInterface(priceOracle).getPrice(userEnteredMarkets[i]);
            require(assetPrice > 0, "invalid price");
            uint256 collateralFactor = m.config.collateralFactor;
            if (supplyBalance > 0 && collateralFactor > 0) {
                uint256 exchangeRate = _getExchangeRate(m);
                collateralValue += (supplyBalance * exchangeRate * assetPrice * collateralFactor) / 1e36 / FACTOR_SCALE;
            }
            if (borrowBalance > 0) {
                debtValue += (borrowBalance * assetPrice) / 1e18;
            }
        }
        return (collateralValue, debtValue);
    }
```

## Impact
A credit account's stake instantly becomes collateral, completely destroying the purpose of credit accounts. 

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L406-#L451
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1016-#L1025
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1032-#L1058

## Tool used

Manual Review

## Recommendation
When calculating liquidity, do not take into account the borrowed amount from a user's creditLimit.

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
The issue above describes a scenario where users will not be able to withdraw their collateral, even though they should be able to. Protocol insolvency should be at least a valid M

**Comment by 0xffff11** [comment]
@ibsunhub I believe it is invalid, but I would like to know your PoV

**Comment by ibsunhub** [comment]
Yes, invalid to me.

A credit account can't redeem if it has borrow balance. However, the candidate shouldn't have any supply before it becomes the credit account. We will check that before giving the credit account.

**Comment by iamjakethehuman** [comment]
Even though a check will be made on the account beforehand, this wouldn't be enough. A credit account can also hold IBTokens by liquidating another user. After liquidating the user, they will not be able to redeem the IBTokens they seized.

**Comment by ibsunhub** [comment]
Yes, it's dup to #304 and #458.

We will add a fix to prevent credit accounts from liquidating.

The whole point of this issue is invalid to me is that we don't expect the credit account will redeem or liquidate. Credit accounts are privilege account that normally will only use borrow function. Credit accounts are trusted party. We will know what these contracts are going to do before making them credit accounts.

**Comment by iamjakethehuman** [comment]
"We will add a fix to prevent credit accounts from liquidating" - this means there is a valid issue with it and it needs to be fixed.
However this issue is present in the code as we have audited it. In fact I have even submitted it myself (#94). There is a valid vulnerability in the code. 
"We don't expect the credit account will redeem or liquidate" - if they aren't expected to do so - restrict them. If they're supposed to be restricted but aren't, this is also a valid Medium finding as code doesn't work as expected. 
Allowing a user to have/ receive funds and not be able to redeem them is a valid M 
Allowing a user to pay (liquidate) in order to receive funds and later being unable to redeem them should also be a valid M (#94)

**Comment by ibsunhub** [comment]
fix: https://github.com/ibdotxyz/ib-v2/pull/55

**Comment by ib-tycho** [comment]
Hi @iamjakethehuman - As I mentioned multiple times in the Discord channel.
> A credit account enables a user, typically a contract, to borrow up to the credit limit without providing collateral. In order to qualify as a credit account, the contract must have a mechanism to calculate its external collateral. For instance, a strategy contract that borrows a single asset and farms CRV on a Curve pool would consider the deposited LP tokens + collectable CRV rewards as external collateral. To become a credit account, the user or protocol needs to submit a request, and Iron Bank will review the code to ensure it complies with our policy

Credit account is considered as TRUSTED. credit account should not be treated as the same as ordinary EOA. That's the reason why we don't think should be Medium.

> Allowing a user to have/ receive funds and not be able to redeem them is a valid M
> Allowing a user to pay (liquidate) in order to receive funds and later being unable to redeem them should also be a valid M

These are true but credit account is not "a user".

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Sponsor comment on this one. 
The credit account role by nature is trusted since you have to trust someone to give them a completely uncollateralized loan. 
> "We don't expect the credit account will redeem or liquidate" - if they aren't expected to do so - restrict them. If they're supposed to be restricted but aren't, this is also a valid Medium finding as code doesn't work as expected.

If a trusted actor is not intended to liquidate then not being able to redeem is not a medium vulnerability. Making sure they don't liquidate is just a preventive measure for a mistake in this case and not a bug.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/98/#issuecomment-1606054969): rejected

**Comment by IAm0x52** [comment]
Fix looks good. Credit accounts can no longer be the liquidator
